shipwright-io/operator

.github/workflows/ci.yml, Makefile, api/v1alpha1/shipwrightbuild_types.go, bundle/manifests/operator.shipwright.io_shipwrightbuilds.yaml, config/crd/bases/operator.shipwright.io_shipwrightbuilds.yaml, hack/check-git-status.sh, hack/install-operator-sdk.sh
- Make `ShipwrightBuild` a cluster-scoped CRD
- Add verification checks to ensure artifacts are correctly generated.
/kind feature
```release-note
NONE
```
=> Make ShipwrightBuild cluster-scoped

.gitignore, Makefile, docs/development/local-development.md, hack/fix-plurals.sh
Allowing users to export `SED_BIN` environment variable, so macOS users can use `gsed` instead. Plus, a few other minor changes.
```release-note
NONE
```
=> Alternative GNU Sed Location

cmd/operator/main.go
Refactoring `main.go`, reorganizing flags and code structure. Pull-request #10 spin-off changes.
```release-note
NONE
```
=> Refactoring Flags

Makefile, hack/install-ko.sh, hack/install-operator-sdk.sh
Exporting `OS` and `ARCH` variables through `Makefile` targets, so `hack/` scripts can be executed on more platforms than "Linux/amd64".
```release-note
NONE
```
=> Multi-Platform Scripts

README.md, api/v1alpha1/doc.go, api/v1alpha1/shipwrightbuild_types.go, bundle/manifests/operator.clusterserviceversion.yaml, bundle/manifests/operator.shipwright.io_shipwrightbuilds.yaml, cmd/operator/main.go, config/crd/bases/operator.shipwright.io_shipwrightbuilds.yaml, config/manifests/bases/operator.clusterserviceversion.yaml, controllers/default_test.go, controllers/result.go, controllers/shipwrightbuild_controller.go, controllers/shipwrightbuild_controller_test.go, controllers/shipwrightbuild_rbac.go, controllers/suite_test.go, controllers/util.go, hack/check-git-status.sh, hack/test-with-envtest.sh, test/common.go
Allowing namespaces to be configurable via `.spec.namespace` attribute, when not informed it uses `shipwright-build` by default.
```yml
---
apiVersion: operator.shipwright.io/v1alpha1
kind: ShipwrightBuild
metadata:
name: shipwright-operator
spec:
targetNamespace: default
```
There is some refactoring as well, notably implementing [Finalizer Pattern][0] in order to detect resource deletion, and handle manifests removal at Reconciler level.
Fixes #6
```release-note
- Introducing `.spec.namespace`, the target namespace where Shipwright-Controller is deployed;
```
[0]: https://book.kubebuilder.io/reference/using-finalizers.html
=> Target Namespace

bundle/manifests/shipwright-operator.clusterserviceversion.yaml, config/default/manager_auth_proxy_patch.yaml, config/manager/manager.yaml
Run operator as non-root instead of a fixed UID. This fixes issues with OpenShift security context constraints.
/kind bug
```release-note
Run operator as non-root instead of using a fixed UID. This allows the operator to run on OpenShift using the "restricted" security context constraint.
```
=> Run operator as non-root

.github/workflows/ci.yml, Makefile, config/catalog/catalog_source.yaml, config/catalog/kustomization.yaml, config/subscription/kustomization.yaml, config/subscription/operator_group.yaml, config/subscription/subscription.yaml, controllers/default_test.go, docs/development/local-development.md, docs/development/olm-development.md, hack/run-operator-catalog.sh, test/kind/config.yaml, test/kind/deploy-registry-post.sh, test/kind/deploy-registry.sh, test/kind/local-registry-cm.yaml, test/kind/verify-kind.sh
This change augments the e2e test suite to simulate the operator's deployment using OLM.
The setup consists of the following components:
- A docker/distribution container registry, running in docker outside of any Kubernetes cluster.
- A KinD cluster that is configured to resolve image refs which use "localhost" as the image registry domain.
- Installing OLM on the KinD cluster.
Once set up, the operator and its associated OLM bundle are built and pushed to the local container registry.
Next, an OLM catalog is built based on the catalog published in operatorhub.io.
The catalog is what allows OLM to find the Tekton operator that Shipwright depends on, and is likewise pushed to the local container registry.
Building the operator, bundle, and catalog with a fully on-cluster registry is …
=>  E2E CI Test for Operator Bundle

bundle/manifests/shipwright-operator.clusterserviceversion.yaml, config/default/manager_auth_proxy_patch.yaml
Update the kube-rbac-proxy image to use v0.8.0, which runs as nonroot.
This change was done in operator-sdk v1.5.0, but was not noted in the migration guide.
See https://github.com/operator-framework/operator-sdk/pull/4402.
/kind bug
```release-note
Update kube-rbac-proxy image to v0.8.0
```
=> Use kube-rbac-proxy v0.8.0

hack/run-operator-catalog.sh
Use the ShipwrightBuild object to verify we can deploy the build controller.
/kind cleanup
```release-note
NONE
```
=> Verify deployment of build controller

Makefile, bundle/manifests/shipwright-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml
This fixes test failures due to the fact that the CSV version of the operator being tested conflicts with the operator in the OperatorHub index image.
- Update the default version to 0.7.1-snapshot so it does not conflict
with the CSV on OperatorHub.
- Update default image location to ghcr.io so we can more easily submit
updates to OperatorHub.
/kind cleanup
```release-note
Update default location of the operator image to ghcr.io/shipwright-io/operator/operator.
```
=> Update operator version and image spec

.github/workflows/ci.yml
Temporarily disabling the catalog build and run test.
This will unblock contributions that currently fail due to failures
running `opm index add`.
Stop-gap until we fully fix #57 
/kind cleanup
```release-note
NONE
```
=> Disable Catalog Build and Run

.github/workflows/ci.yml, .golangci.yml, controllers/shipwrightbuild_controller.go, controllers/shipwrightbuild_controller_test.go, controllers/suite_test.go
Closes #35 
```release-note
NONE
```
=> Use golangci-lint

Makefile, README.md, bundle/manifests/shipwright-operator.clusterserviceversion.yaml, cmd/operator/kodata/release.yaml, config/manager/kustomization.yaml, config/manifests/bases/shipwright-operator.clusterserviceversion.yaml, config/rbac/kustomization.yaml, config/rbac/shipwright_build_aggregate_role.yaml, config/rbac/shipwright_build_aggregate_role_binding.yaml, docs/shipwrightbuild.md
- Deploy Shipwright Build v0.9.0
- Update version to release candidate.
- Describe the fields in the ShipwrightBuild CRD.
- Indicate which version of Shipwright Builds is installed.
- Add installation instructions to the README.
- Remove instruction that the target namespace needs to be created
first.
Fixes #51 
/kind feature
/kind documentation
```release-note
Deploy ShipwrightBuild v0.9.0 and improve installation documentation.
```
=> Deploy Shipwright Build v0.9.0

.github/workflows/ci.yml, .github/workflows/release.yaml, Makefile, docs/development/local-development.md, go.mod, go.sum
Updating everything to Go 1.18. Had to update logic in the Makefile to not use `go get` anymore in favor of `go install`.
Fixes #73
```release-note
We now build our binaries with Go 1.18
```
=> Update Go to 1.18

bundle/manifests/shipwright-operator.clusterserviceversion.yaml, config/rbac/role.yaml, controllers/shipwrightbuild_rbac.go
Fixing the missing permissions to delete the aggregated cluster roles when removing a `ShipwrightBuild` object.
Still familiarizing on how to develop with this repo, so cannot provide e2e test case as described in #71, but we need the fix in v0.10.
```release-note
Adding missing permissions for the operator to cleanup the aggregated cluster roles that Shipwright v0.9 introduced.
```
=> Add permission to manage aggregated clusterroles

.github/workflows/release.yaml
In 0b91c10b, the CSV stored in git was altered to include the `ko://`
image reference. The real image reference is generated at build time,
and its "resolved" CSV is stored in an ignored directory. This
unfortunately broke the release GitHub action, which greps the in-tree
CSV fo images to sign.
This updates the release action to look at the "resolved" CSV in the
`_output/olm` directory when searching for images to sign. This also
updates cosign-installer to v2.3.0.
/kind bug
```release-note
Fix bug that caused the signing of the operator image to fail.
```
=> Fix signing of released image

.github/workflows/ci.yml, .github/workflows/release.yaml, go.mod
Updating GitHub actions like in https://github.com/shipwright-io/build/pull/1085
Fixes #104
```release-note
NONE
```
=> Update GitHub actions and Go to 1.19

.github/workflows/ci.yml, Makefile, docs/development/local-development.md, docs/development/olm-development.md, go.mod, hack/install-ko.sh
Update build to use golang 1.20.x, and ko to v0.15.0 (latest release).
```release-note
NONE
```
=> Update go to 1.20 and ko to v0.15.0

.github/workflows/release.yaml
Update go version in the release workflow. This was missed in the go bump pull request.
See #161 
```release-note
NONE
```
=> Update to go 1.20 for release

bundle/manifests/shipwright-operator.clusterserviceversion.yaml, config/manifests/bases/shipwright-operator.clusterserviceversion.yaml
- Set `spec.minKubeVersion` to `1.23.13`
Fixes #94
```release-note
Minimum k8s version is now 1.23.13
```
=> chore: Add CSV `spec.minKubeVersion`

Makefile, bundle.Dockerfile, bundle/manifests/shipwright-operator-metrics-service_v1_service.yaml, bundle/manifests/shipwright-operator.clusterserviceversion.yaml, bundle/metadata/annotations.yaml, config/default/manager_auth_proxy_patch.yaml, config/manager/manager.yaml, config/prometheus/monitor.yaml, config/rbac/auth_proxy_service.yaml, hack/install-operator-sdk.sh
Upgrade operator-sdk to v1.18, bringing in the following enhancements:
- Ability to use image digests in the released operator bundle (v1.18.0)
- Fix deployment to align with operator-sdk requirements.
```release-note
Add `control-plane` label to operator deployment so it supports bundling with operator-sdk v1.18
```
=> Update operator-sdk to v1.18

Makefile, controllers/suite_test.go
Add option to skip the reconcile tests that utilize EnvTest. These tests have a noticeable amout of setup time, and failure cases can take over 30 seconds each to be identified due to timeouts. The skip option will execute test cases that do not require EnvTest, which are more likely to be standard golang unit tests that execute quickly.
This also drops the `-p 1` parameter passed to `go test`, which allows go to execute tests in parallel.
```release-note
NONE
```
=> Skip EnvTest Tests

DEVELOPMENT.md, README.md
This adds a developer guide that serves as an entrypoint for new code contributors. The operator project has existing documentation for local and OLM development, however it is buried in a nested directory that is not easy to find. Those documents also miss critical foundational knowledge, such as dev prerequisites and an understanding of OLM.
This PR also fixes the broken link to the contributor guidelines.
/kind documentation
```release-note
NONE
```
=> Add Developer Guide

controllers/default_test.go, controllers/shipwrightbuild_controller.go
- Filter Crds before deleting resources because operator should not delete Crds when shipwright instance is deleted
Fixes #173 
```release-note
Shipwright's Build CRDs are no longer deleted when the `ShipwrightBuild` object is deleted.
```
=> Operator should not delete CRDs

.github/workflows/ci.yml, .github/workflows/release.yaml, DEVELOPMENT.md, Makefile, docs/development/local-development.md, docs/development/olm-development.md, go.mod, go.sum, hack/install-ko.sh
- Updated the Go mod version to 1.21
- fixes #189 
=> Updated go modules to 1.21

.github/workflows/ci.yml
Update our CI-oriented GitHub actions to run when commits merge in a `release-v*` branch, or a pull request is opened against a `release-v*` branch. With this change, future release branches will automatically have CI checks enabled. This commit should be backported to enable CI in a prior release branch.
This implements a portion of SHIP-0038.
https://github.com/shipwright-io/community/issues/85
```release-note
NONE
```
=> [release-v0.12] SHIP-0038: Run CI on Release Branches

.github/workflows/ci.yml
Update our CI-oriented GitHub actions to run when commits merge in a `release-v*` branch, or a pull request is opened against a `release-v*` branch. With this change, future release branches will automatically have CI checks enabled. This commit should be backported to enable CI in a prior release branch.
This implements a portion of SHIP-0038.
See also https://github.com/shipwright-io/community/issues/85
```release-note
NONE
```
/kind cleanup
=> SHIP-0038: Run CI on Release Branches

.github/workflows/release.yaml
Update the release workflow to accept a git reference as a parameter. This will be used to check out the appropriate release branch when generating artifacts and release notes.
The action was also updated with the following:
- Use the (new?) inputs context, instead of relying on the inputs key existing in the `github.events` payload.
- Update the checkout and setup-go actions to more recent versions.
Part of #197 
/kind cleanup
```release-note
NONE
```
=> SHIP-0038: Add Git Ref to Release Workflow

controllers/shipwrightbuild_controller.go, pkg/common/testdata/test-truncate-crd-field.yaml, pkg/common/util.go, pkg/common/util_test.go
Adding a TruncateField transformer and using it to truncate CRD description fields from the `kodata/release.yaml` manifest. The CRDs for Shipwright Build objects are very large, resulting in a validation error from Kubernetes when we try to create the CRDs with Manifestival.
Partially addresses #184 
```release-note
Tructate descriptions in Shipwright custom resource definitions to 50 characters.
```
=> Truncate CRD Description Fields to 50 Characters

test/common.go
Use manifestival to parse the build strategies in the sample buildstrategies directory. This will make it easier for tests to decode YAML data for build strategies.
/kind cleanup
```release-note
NONE
```
=> Parse Build Strategies with Manifestival

.github/workflows/ci.yml, .github/workflows/release.yaml
- Update ci to use checkout@v4, setup-go@v5
- Update cosign-installer to v3
Note - updating cosign is needed so we use the latest version. Older versions can't talk to Fulcio - see [sigstore announcement](https://blog.sigstore.dev/tuf-root-update/)
/kind cleanup
```release-note
NONE
```
=> Bump GitHub Actions

.github/workflows/release.yaml
Add --yes to cosign command. Newer cosign by default has an interactive prompt. Pass the `--yes` option to acknowledge the prompt ahead of time.
/kind bug
/kind cleanup
```release-note
NONE
```
=> fix: Add --yes to cosign

Makefile, bundle/manifests/shipwright-operator.clusterserviceversion.yaml
Update version on `main` branch so it is clear that `v0.14.0` is under active development.
/kind feature
```release-note
Bump version to v0.14.0-rc0
```
=> Bump Version to v0.14.0

pkg/tekton/tekton.go, pkg/tekton/tekton_test.go
Starting in Tekton Operator v0.58.0, TektonConfig objects must set a value for `keep` or `keepSince` if the pruner is enabled [1]. If Shipwright bootstraps the TektonConfig object and does not set a value for `.spec.pruner.keep` (or `.keepSince`), it risks failing to reconcile the TektonConfig instance or worse [2].
Fixing by setting the `keep` value to match the Tekton operator default.
Fixes #231
[1] https://github.com/tektoncd/operator/pull/410
[2] https://github.com/tektoncd/operator/issues/2450
```release-note
When the operator creates a TektonConfig object, enable the pruner with a default `keep` …
```
=> fix: Set TektonConfig Pruner

docs/development/releasing.md, hack/release-operatorhub.sh
Add a procedure and script to publish an operator release to the upstream k8s community operators OperatorHub. The script requires the user to fork the upstream k8s operators repsository and afterwards submit a pull request by hand.
In the future this procedure/script can be added to our release automation so when an operator release is published, we initiate the process to update the upstream OperatorHub catalog.
Fixes #132 
/kind documentation
```release-note
NONE
```
=> doc: Procedure to Publish Operator on OperatorHub

kodata/release.yaml
Update operator to deploy Shipwright Build
nightly-2025-02-24-1740373406 components.
Changes include updates to the build CRDs
/kind feature
```release-note
Update operator to deploy Shipwright Build nightly-2025-02-24-1740373406 components.
```
=> feat: Update operator to deploy latest nightly Shipwright Build

kodata/release.yaml
Changes include updated images for 0.15.2 version
/kind feature
```release-note
Update operator to deploy Shipwright Build 0.15.2 components.
```
=> feat: Update Shipwright Builds to v0.15.2

.github/workflows/ci.yml, .github/workflows/release.yaml, go.mod
Calling Verify with a VerifyOptions.KeyUsages that contains ExtKeyUsageAny unintentionally disabledpolicy validation. This only affected certificate chains which contain policy graphs, which are rather uncommon. Ref: [CVE-2025-22874](https://pkg.go.dev/vuln/GO-2025-3749)
```release-note
NONE
```
=> Update Golang to 1.24.4 to mitigate CVE-2025-22874

controllers/buildstrategies_test.go, controllers/default_test.go, controllers/shipwrightbuild_controller.go, controllers/shipwrightbuild_controller_test.go, controllers/suite_test.go
Added a check for tektonconfig before progressing in the reconciliation process.
Fixes #167
- [ x ] Includes tests if functionality changed/was added
- [ x ] Release notes block has been filled in, or marked NONE
```
Fix: build status reports ready early when tektonconfig is at Error/not available state
```
=> Fix: Add a check for tektonconfig status

.github/workflows/release.yaml
Release tag is expected in X.Y.Z format whereas previous tag is expected in vX.Y.Z format. The reason for this is that the release tag is used by Makefile command which expects version without leading v. However, this also creates the Github release tag without leading "v" in the actions/create-release step, which has to be manually edited in draft release note before publishing. This PR expects release tag in vX.Y.Z format and strips leading "v" before setting VERSION env.
Fixes #224 
```release-note
NONE
```
=> Fixed Release Tag Format Bug
